// <auto-generated />
using System;
using ApiPlayLists.AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiPlayLists.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328051636_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiPlayLists.Entities.PlayList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UrlSlug")
                        .IsUnique();

                    b.ToTable("playlists");
                });

            modelBuilder.Entity("ApiPlayLists.Entities.PlayListCover", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Img")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("PlayListId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayListId")
                        .IsUnique();

                    b.ToTable("playlist_covers");
                });

            modelBuilder.Entity("ApiPlayLists.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Artist")
                        .HasColumnType("text");

                    b.Property<string>("Genere")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailableInSpotify")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("PlayListId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayListId");

                    b.ToTable("songs");
                });

            modelBuilder.Entity("ApiPlayLists.Entities.SongAudio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Audio")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SongId")
                        .IsUnique();

                    b.ToTable("song_audios");
                });

            modelBuilder.Entity("ApiPlayLists.Entities.SongCover", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Img")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SongId")
                        .IsUnique();

                    b.ToTable("song_covers");
                });

            modelBuilder.Entity("ApiPlayLists.Entities.PlayListCover", b =>
                {
                    b.HasOne("ApiPlayLists.Entities.PlayList", "PlayList")
                        .WithOne("Cover")
                        .HasForeignKey("ApiPlayLists.Entities.PlayListCover", "PlayListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayList");
                });

            modelBuilder.Entity("ApiPlayLists.Entities.Song", b =>
                {
                    b.HasOne("ApiPlayLists.Entities.PlayList", "PlayList")
                        .WithMany("Songs")
                        .HasForeignKey("PlayListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayList");
                });

            modelBuilder.Entity("ApiPlayLists.Entities.SongAudio", b =>
                {
                    b.HasOne("ApiPlayLists.Entities.Song", "Song")
                        .WithOne("Audio")
                        .HasForeignKey("ApiPlayLists.Entities.SongAudio", "SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("ApiPlayLists.Entities.SongCover", b =>
                {
                    b.HasOne("ApiPlayLists.Entities.Song", "Song")
                        .WithOne("Cover")
                        .HasForeignKey("ApiPlayLists.Entities.SongCover", "SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("ApiPlayLists.Entities.PlayList", b =>
                {
                    b.Navigation("Cover");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("ApiPlayLists.Entities.Song", b =>
                {
                    b.Navigation("Audio");

                    b.Navigation("Cover");
                });
#pragma warning restore 612, 618
        }
    }
}
